In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X=iris.data

In [10]:
y=iris.target

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from keras.utils import to_categorical

In [14]:
y=to_categorical(y)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scaler_object=MinMaxScaler()

In [20]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train=scaler_object.transform(X_train)

In [22]:
scaled_X_test=scaler_object.transform(X_test)

In [23]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

W0807 17:21:37.663451 16064 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0807 17:21:38.269777 16064 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0807 17:21:38.439360 16064 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0807 17:21:38.759948 16064 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0807 17:21:38.859679 16064 deprecation_wrapper.py:119] From C:\ProgramData\Anac

In [26]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

W0807 17:23:15.106292 16064 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0807 17:23:15.226968 16064 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/150
 - 2s - loss: 1.0542 - acc: 0.3400
Epoch 2/150
 - 0s - loss: 1.0481 - acc: 0.3400
Epoch 3/150
 - 0s - loss: 1.0421 - acc: 0.3400
Epoch 4/150
 - 0s - loss: 1.0358 - acc: 0.3400
Epoch 5/150
 - 0s - loss: 1.0298 - acc: 0.3400
Epoch 6/150
 - 0s - loss: 1.0249 - acc: 0.3500
Epoch 7/150
 - 0s - loss: 1.0191 - acc: 0.3500
Epoch 8/150
 - 0s - loss: 1.0142 - acc: 0.3400
Epoch 9/150
 - 0s - loss: 1.0089 - acc: 0.3400
Epoch 10/150
 - 0s - loss: 1.0041 - acc: 0.3400
Epoch 11/150
 - 0s - loss: 0.9993 - acc: 0.3400
Epoch 12/150
 - 0s - loss: 0.9948 - acc: 0.3400
Epoch 13/150
 - 0s - loss: 0.9903 - acc: 0.3400
Epoch 14/150
 - 0s - loss: 0.9858 - acc: 0.3400
Epoch 15/150
 - 0s - loss: 0.9814 - acc: 0.3700
Epoch 16/150
 - 0s - loss: 0.9772 - acc: 0.4100
Epoch 17/150
 - 0s - loss: 0.9727 - acc: 0.4000
Epoch 18/150
 - 0s - loss: 0.9678 - acc: 0.4300
Epoch 19/150
 - 0s - loss: 0.9628 - acc: 0.4400
Epoch 20/150
 - 0s - loss: 0.9574 - acc: 0.5000
Epoch 21/150
 - 0s - loss: 0.9522 - acc: 0.5300
E

In [29]:
predictions=model.predict_classes(scaled_X_test)

In [32]:
y_test=y_test.argmax(axis=1)

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [34]:
confusion_matrix(y_test,predictions)

array([[19,  0,  0],
       [ 0,  5, 10],
       [ 0,  0, 16]], dtype=int64)

In [35]:
accuracy_score(y_test,predictions)

0.8

In [37]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.33      0.50        15
           2       0.62      1.00      0.76        16

   micro avg       0.80      0.80      0.80        50
   macro avg       0.87      0.78      0.75        50
weighted avg       0.88      0.80      0.77        50



In [38]:
model.save('iris_model.h5')

In [39]:
from keras.models import load_model

In [40]:
new_model=load_model('iris_model.h5')